# Generated by Django 4.0.2 on 2022-02-17 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super_type', '0001_initial'),
        ('supers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Super',
            new_name='Supers',
        ),
    ]
