# Generated by Django 4.0.2 on 2022-02-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0002_rename_super_supers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supers',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
