# Generated by Django 4.0.2 on 2022-02-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0003_alter_supers_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supers',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
